language: node_js
node_js:
    - "node"

script:
    - npm run build

before_deploy:
    - find . -not -path "./docs" -not -path "./docs/*" -delete
    - mv ./docs/* .
    - rm -rf ./docs

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
    target-branch: gh-pages

notifications:
    email:
        recipients:
        - KSDaemon@ya.ru
        on_success: change
        on_failure: always
